config/routes.rb
Rails.application.routes.draw do
  root to: "spectacles#index"

  resources :spectacles do
    resources :performs
  end



  resources :performs do
    collection do
      get :top
    end
    collection do
      get :dimanche
    end
    collection do
      get :samedi
    end
    collection do
      get :vendredi
    end
    collection do
      get :jeudi
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/perform.rb
class Perform < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  has_many_attached :photos
  belongs_to :spectacle
end

app/models/spectacle.rb
class Spectacle < ApplicationRecord
  has_many :performs, dependent: :destroy
  has_many_attached :photos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home

      #@performs = Perform.all
      @performs = Perform.geocoded

        # The `geocoded` scope filters only performs with coordinates
      @markers = @performs.map do |perform|
        {
          lat: perform.latitude,
          lng: perform.longitude,

          info_window_html: render_to_string(partial: "performs/info_window", locals: {perform: perform}), # Pass the perform to the partial
          marker_html: render_to_string(partial: "performs/marker", locals: {perform: perform}), # Pass the perform to the partial
          #start_time_html: render_to_string(partial: "performs/start_time"), locals: {perform: perform}
        }


      end

  end
end

app/controllers/performs_controller.rb
class PerformsController < ApplicationController
  before_action :set_perform, only: %i[ show edit update destroy ]


  def day(day)
    @performs = Perform.order(:start).select do |perform|
      perform.start.day?
    end
  end

  def jeudi
    @performs = Perform.order(:start).select do |perform|
      perform.start.thursday?
    end
  end

  def vendredi
    @performs = Perform.order(:start).select do |perform|
      perform.start.friday?
    end
  end

  def samedi
    @performs = Perform.order(:start).select do |perform|
      perform.start.saturday?
    end
    @spectacle_cover = "cghl0ue5m127ziptd81qfomp7561"
  end

  def dimanche
    @performs = Perform.order(:start).select do |perform|
      perform.start.sunday?
    end
  end

  #work only for new, create
  #before_action :set_spectacle, only: %i[ new edit create update destroy ]


  def top
    @performs = Perform.order(:start).where(collected: true)

    @markers = @performs.map do |perform|
      {
        lat: perform.latitude,
        lng: perform.longitude,

        info_window_html: render_to_string(partial: "info_window", locals: {perform: perform}), # Pass the perform to the partial
        marker_html: render_to_string(partial: "marker", locals: {perform: perform}), # Pass the perform to the partial
        #start_time_html: render_to_string(partial: "start_time"), locals: {perform: perform}
      }

    end
  end

  # GET /performs or /performs.json
  def index
    #@performs = Perform.all

    @performs = Perform.order(:start)



    #@performs = Perform.geocoded
    # The `geocoded` scope filters only performs with coordinates

    #@collecteds = Perform.where(collected: true)
    # collected == true filter

    @markers = @performs.map do |perform|
      {
        lat: perform.latitude,
        lng: perform.longitude,

        info_window_html: render_to_string(partial: "info_window", locals: {perform: perform}), # Pass the perform to the partial
        marker_html: render_to_string(partial: "marker", locals: {perform: perform}), # Pass the perform to the partial
        #start_time_html: render_to_string(partial: "start_time"), locals: {perform: perform}
      }

    end
  end

  # GET /performs/1 or /performs/1.json
  def show
  end

  # GET /performs/new
  def new
    @spectacle = Spectacle.find(params[:spectacle_id]) #si je definis ça dans set_spectacle before action, edit update ne fonctionne plus
    @perform = Perform.new
    @perform.spectacle = @spectacle

  end

  # GET /performs/1/edit
  def edit
    @perform = Perform.find(params[:id])

  end

  # POST /performs or /performs.json
  def create
    #build perform with params -> raised ok
    @perform = Perform.new(perform_params)

    #find spectacle useless ? already set if défine in set spectacle -> buggy edit
    # find assoiated spectacle -> raised ok
    @spectacle = Spectacle.find(params[:spectacle_id])

    # associe perform et spectacle à la creation du perform -> raised ok
    @perform.spectacle = @spectacle
    # create a peform id -> raised ok
    @perform.save


    respond_to do |format|
      if @perform.save
        format.html { redirect_to perform_url(@perform), notice: "Perform was successfully created." }
        format.json { render :show, status: :created, location: @perform }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @perform.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /performs/1 or /performs/1.json
  def update
    respond_to do |format|
      if @perform.update(perform_params)
        #format.html
        format.html {redirect_to top_performs_path}
        #format.html { redirect_to perform_url(@perform), notice: "Perform was successfully updated." }
        format.json { render :show, status: :ok, location: @perform }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @perform.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /performs/1 or /performs/1.json
  def destroy
    @perform.destroy

    respond_to do |format|
      format.html { redirect_to performs_url, notice: "Perform was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.


    def set_perform
      @perform = Perform.find(params[:id])#params available in class methods define in before_action
      # si start est different de nil tu formate la date, sinon tu fais rien - @date ne marche que pour show
      @date = @perform.start != nil ? (@perform.start.strftime('%I:%M | %a %d %^b')) : ()
      #@date = !@perform.start.nil?
    end

    def set_spectacle
      # set_spectacle cause bugs in edit, update, destroy
      #@spectacle = Spectacle.find(params[:spectacle_id])
    end

    # Only allow a list of trusted parameters through.
    def perform_params
      params.require(:perform).permit(:spectacle_id, :address, :start, :collected)
    end
end

app/controllers/spectacles_controller.rb
class SpectaclesController < ApplicationController

  before_action :set_spectacle, only: %i[ show edit update destroy ]

  def index
    @spectacles = Spectacle.all
    @spectacle_cover = "cghl0ue5m127ziptd81qfomp7561"

  end

  def show
  end

  def new
    @spectacle = Spectacle.new
  end

  def edit
  end

  def create
    @spectacle = Spectacle.new(spectacle_params)
    respond_to do |format|
      if @spectacle.save
        format.html { redirect_to spectacle_url(@spectacle), notice: "spectacle was successfully created." }
        format.json { render :show, status: :created, location: @spectacle }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @spectacle.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @spectacle.update(spectacle_params)
        format.html { redirect_to spectacle_url(@spectacle), notice: "spectacle was successfully updated." }
        format.json { render :show, status: :ok, location: @spectacle }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @spectacle.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @spectacle.destroy

    respond_to do |format|
      format.html { redirect_to spectacles_url, notice: "Spectacle was successfully destroyed." }
      format.json { head :no_content }
    end
  end


  private

  def set_spectacle
    @spectacle = Spectacle.find(params[:id])
  end

  def spectacle_params
    params.require(:spectacle).permit(:title, :company, :description, photos: [])
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_navbar.html.erb
<div class="navbar sticky-top navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%#= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
      <%#= cl_image_tag("mdehrk5lirpb8rdtjobn", width: 512, crop: :fill) %>
      <%= image_tag "ico-N-logo.svg" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <%# if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item active">
            <%= link_to "spectacles", spectacles_path, class: "nav-link" %>
          </li>
          <li class="nav-item active">
            <%= link_to "représentations", performs_path, class: "nav-link" %>
          </li>
          <li class="nav-item active">
            <%= link_to "jeudi", jeudi_performs_path, class: "nav-link" %>
          </li>
          <li class="nav-item active">
            <%= link_to "vendredi", vendredi_performs_path, class: "nav-link" %>
          </li>
          <li class="nav-item active">
            <%= link_to "samedi", samedi_performs_path, class: "nav-link" %>
          </li>
          <li class="nav-item active">
            <%= link_to "dimanche", dimanche_performs_path, class: "nav-link" %>
          </li>
          <li class="nav-item active">
            <%= link_to "selection", top_performs_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", "#", class: "dropdown-item", data: {turbo_method: :delete} %>
            </div>
          </li>
        <%# else %>
          <!--li class="nav-item"-->
            <%#= link_to "Login", new_user_session_path, class: "nav-link" %>
          <!--/li-->
        <%# end %>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Festival</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.js"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
  <%= render partial: "layouts/navbar" %>

</div>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/_map.html.erb
<div style="width: 100%; height: 600px; margin-top:3rem;"
  data-controller="map"
  data-map-markers-value="<%= markers.to_json %>"
  data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
</div>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>
<p class="mb-0"><s>this map doesn't display markers</s></p>
<p>markers display since i define home class method in application_controller</p>
<p><%= link_to "map with markers managed by perform controller", performs_path %>
</p>
<p><%= link_to "New perform", new_perform_path %></p>
<div>
<%= cl_image_tag("pcwp7iipgft01ofhzmurfh0m030u",
      width: 400, height: 300, crop: :fill) %>

</div>
<%#= render partial: "performs/start_time" %>
<%#= render partial: "performs/perform" %>

<div style="width: 100%; height: 600px;"
  data-controller="map"
  data-map-markers-value="<%= @markers.to_json %>"
  data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
</div>

app/views/performs/_card_product.html.erb
<div class="card-product">
    <% perform.spectacle.photos.each do |photo| %>
    <%= link_to perform.spectacle do %>
      <%= cl_image_tag photo.key, height: 200, width: 200, crop: :fill %>
      <% end %>
    <% end %>
  <%# <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/skateboard.jpg" /> %>
  <div class="card-product-infos">
    <h2><%= perform.spectacle.title %></h2>
      <p>
        <% date = perform.start %>
        <%= date.strftime('%H:%M | %a %d %^b') if !date.nil? %>
      </p>
      <%# <p><strong>Address : </strong> %>
        <%#= perform.address %>
      <%# </p> %>
      <p><%= render "performs/check", perform: perform, spectacle:spectacle %></p>
  </div>
</div>

app/views/performs/_form.html.erb
<%= simple_form_for [@spectacle, @perform] do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
<%= @perform.spectacle.title %>
<p class="mb-0"><strong>spectacle :</strong><%= @perform.spectacle.title %> (@perform.spectacle.title)</p>
<p class="mb-0"><strong>company :</strong><%= @perform.spectacle.company %> (@perform.spectacle.company)</p>
<p class="mb-0"><strong>spectacle id :</strong><%= @perform.spectacle.id %> (@perform.spectacle.id)</p>
<p class="mb-0"><strong>perform.spectacle_id :</strong><%= @perform.spectacle_id %> (@perform.spectacle_id)</p>
<p class="mb-0"><strong>perform.id :</strong><%= @perform.id %> (@perform.id)</p>
  <div class="form-inputs">

    <%#= f.input :start, as: :datetime %>
    <%#= f.association :spectacle %>

    <%= f.input :start, as: :datetime, label:'Launch Date & Time', class: "form-control form-control-lg", input_html: {value: params[:start]}, wrapper_html: { class: 'mb-3' }, html5: true %>

   <%# mapbox address autocomplete %>
    <p><strong>Current address : </strong><%= @perform.address %><p>
    <%= f.input :address,
      input_html: {
        data: {address_autocomplete_target: "address"},
        class: "d-none"
      },
      wrapper_html: {
        data: {
          controller: "address-autocomplete",
          address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]
        }
      }
    %>
    <%= f.input :collected %>
  </div>


  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/performs/_info_window.html.erb
<div class="p4">
  <p class="mb-0"><strong><%= perform.spectacle.title %></strong></p>
  <p class="mb-0">collected ? : <%= perform.collected %></p>
<p>formulaire :</p>
  <%= simple_form_for(perform) do |f| %>
  <%= f.input :collected %>
  <% end %>
</div>

app/views/performs/_list_per_day.html.erb
<div id="collecteds" class="cards">
  <% @performs.each do |perform| %>
        <div class="card no_link">
      <%= link_to perform do %>
          <%= render perform %>

      <% end %>
      <div class="check px-4 pb-4">
        <%= render "performs/check", perform: perform %></div>
      </div>
  <% end %>
</div>

app/views/performs/_map.html.erb
<div style="width: 100%; height: 400px; margin-top:3rem; margin-bottom:3rem;"
  data-controller="map"
  data-map-markers-value="<%= markers.to_json %>"
  data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
</div>

app/views/performs/_marker.html.erb
<%#= image_tag "logo.png", height: 30, width: 30, alt: "Logo" %>
<div class="badge rounded-pill bg-primary fs-6">
  <% date = perform.start %>
  <%#= date.nil? => false %>
  <%#= !date.nil? => true %>
  <%#= formate la date si il est vrai quelle n'est pas nulle %>
  <%= date.strftime('%H:%M') if !date.nil? %>

</div>

app/views/performs/_middle_perform.html.erb
<div class="card no_link">
  <div class="p-4">
    <% perform.spectacle.photos.each do |photo| %>
      <%= cl_image_tag photo.key, height: 80, width: 80, crop: :fill %>
    <% end %>
      <p><strong><%= perform.spectacle.title %></strong></p>
    <%= link_to perform.spectacle do %>
      <p class="mb-0">
        <% date = perform.start %>
        <%= date.strftime('%H:%M | %a %d %^b') if !date.nil? %>
      </p>
      <p class="mb-0"><strong>Address : </strong>
        <%= perform.address %>
      </p>

    <% end %>
    <div class="">
      <%= render "performs/check", perform: perform, spectacle:spectacle %>
    </div>
  </div>
</div>

app/views/performs/_perform.html.erb
<div class="img_container">
  <%#= cl_image_tag("#{perform.spectacle.photos}", height: 450, width: 800, :crop=>"limit") %>
  <% perform.spectacle.photos.each do |photo| %>
    <%= cl_image_tag photo.key, height: 450, width: 800, crop: :fill %>
  <% end %>
  <%# c'est mis a fonctionner d'un coup - peut être y à t'il une latence avec cloudinary,
  j'ai eu plusieur fois cette impression en liant des images %>


  <%# perform.spectacle.photos.each do |photo| %>
    <%#= cl_image_tag("#{photo}", height: 900, width: 1600, :crop=>"limit") %>
  <%# end %>


</div>
<div id="<%= dom_id perform %>" class="p-4">
  <h2 class="pt-4">
    <%= perform.spectacle.title %>
  </h2>
  <p class="mb-0">
    <strong>Date:</strong>
    <%= perform.start != nil ? (perform.start.strftime('%H:%M | %a %d %^b')) : () %>
    <%#= perform.start.strftime('%I:%M | %a %d %B') %>
  </p>
  <p class="mb-0">
  <strong>@Date:</strong>
  <%= @date %>

  </p>
  <p class="mb-0">
    <strong>Address:</strong>
    <%= perform.address %>
  </p>

  <p class="mb-0">
    <strong>Collected:</strong>
    <%= perform.collected %>
  </p>



</div>

app/views/performs/edit.html.erb
<h1>Editing perform</h1>
    <% @perform.spectacle.photos.each do | photo | %>
      <%= cl_image_tag photo.key, height: 150, width: 200, crop: :fill %>
      <p><strong>photo key :</strong> <%= photo.key %></p>
    <% end %>
<%#= cl_image_tag("#{@perform.spectacle.photo}", height: 90, width: 160, :crop=>"limit") %></strong></p>
<p class="mb-0"><strong>spectacle :</strong><%= @perform.spectacle.title %> (@perform.spectacle.title)</p>
<p class="mb-0"><strong>company :</strong><%= @perform.spectacle.company %> (@perform.spectacle.company)</p>
<p class="mb-0"><strong>spectacle id :</strong><%= @perform.spectacle.id %> (@perform.spectacle.id)</p>
<p class="mb-0"><strong>perform.spectacle_id :</strong><%= @perform.spectacle_id %> (@perform.spectacle_id)</p>
<p class="mb-0"><strong>perform.id :</strong><%= @perform.id %> (@perform.id)</p>

<div class="card p-4">
  <%= render "form" %>
</div>

<br>

<div>
  <%= link_to "Show this perform", @perform %> |
  <%= link_to "Back to performs", performs_path %> |
</div>

app/views/performs/edit.turbo_stream.erb
<%#= turbo_stream.append "performs", @perform %>
<% turbo_stream.update("card_45")%>

app/views/performs/new.html.erb
<h1>New perform</h1>

  <div class="d-flex mb-4">
    <div>
      <% @spectacle.photos.each do |photo| %>
      <%= cl_image_tag photo.key, height: 150, width: 200, crop: :fill %>
      <% end %>
    </div>
    <ul>
      <li><strong>Spectacle : </strong><%= @spectacle.title %> (@spectacle.title)</li>
      <li><strong>ID : </strong><%= @spectacle.id %> (@spectacle.id)</li>
    </ul>
  </div>


<div class="card p-4">
  <%= render "form" %>
  <%#= render "form", perform: @perform, spectacle:@spectacle %>

</div>
<br>

<div>
  <%= link_to "Back to performs", performs_path %>
</div>

app/views/performs/samedi.html.erb
<h1 class="first_title"> Samedi</h1>

<div class="banner mb-4" style="background-image: linear-gradient(rgba(0,0,0,0.1),rgba(0,0,0,0.2)), url(<%= cl_image_path @spectacle_cover %>);">
<div class="container">
  <h1>Prochaine représentation <strong>tech skills</strong> to <strong>creative people</strong>!</h1>
  <p>Mettre ici le prochain spectacles avec un compteur "commence dans  ... minutes</p>
  <a class="btn btn-flat" href="#">Apply now</a>
  </div>

</div>

<%= render "list_per_day" %>

app/views/performs/show.html.erb
<p style="color: green"><%= notice %></p>
<div id="show" class="card p-4">

  <%= render @perform %>




  <div>
    <p>
      <%= link_to "Back", :back %> |
      <%= link_to "Editer cette représentation", edit_perform_path(@perform) %> |
      <%= link_to "Delete",
      perform_path(@perform),
      data: {turbo_method: :delete, turbo_confirm: "delete this spectacle ?"} %>
    </p>
  </div>

</div>

app/views/performs/vendredi.html.erb
<h1 class="first_title">Vendredi</h1>
<%= render "list_per_day" %>

app/views/spectacles/_form.html.erb
<%= simple_form_for(@spectacle) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <div>
    <% @spectacle.photos.each do | photo | %>
      <%= cl_image_tag photo.key, height: 150, width: 200, crop: :fill %>
      <p><strong>photo key :</strong> <%= photo.key %></p>
    <% end %>
  </div>
    <%= f.input :photos, as: :file, input_html:{ multiple: true } %>
    <%= f.input :title %>
    <%= f.input :company %>
    <%= f.input :description %>

  </div>


  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/spectacles/_spectacle.html.erb
<div class="img_container">
  <%#= cl_image_tag spectacle.photo.key, height: 300, width: 400, crop: :fill %>
 <% spectacle.photos.each do |photo| %>
  <%= cl_image_tag photo.key, height: 900, width: 1600, crop: :fill %>
<% end %>
</div>
<div id="<%= dom_id spectacle %>" class="p-4">
  <h2 class="big-title pt-4">
    <%= spectacle.title %>
  </h2>
  <p><strong>- <%= spectacle.company %></strong></p>


</div>

app/views/spectacles/edit.html.erb
<h1>Editing spectacle</h1>
<%= @spectacle.title %>

<div class="card p-4">
  <%= render "form", spectacle: @spectacle %>
</div>

<br>

<div>
  <%= link_to "Show this spectacle", @spectacle %> |
  <%= link_to "Back to spectacles", spectacles_path %>
</div>

app/views/spectacles/index.html.erb
<p style="color: green"><%= notice %></p>

<h1 class="first_title">Tous les spectacles</h1>




<p><%= link_to "create spectacle", new_spectacle_path %></p>

<div id="spectacles" class="cards">
  <% @spectacles.each do |spectacle| %>
        <div class="card no_link">
      <%= link_to spectacle do %>
          <%= render spectacle %>
      <% end %>
        </div>
  <% end %>
</div>

app/views/spectacles/new.html.erb
<h1>New spectacle</h1>
<div class="card p-4">
  <%= render "form", spectacle: @spectacle %>
</div>

<br>

<div>
  <%= link_to "Back to spectacles", spectacles_path %>
</div>

app/views/spectacles/show.html.erb
<p style="color: green"><%= notice %></p>
<div id="show" class="card p-4">
  <%= render @spectacle %>
  <p class="">
    <%= @spectacle.description %>
  </p>
  <p>Représentations</p>
  <%#= render "performs", :spectacle(@spectacle) %>
  <p>* * * * * * * * * * *</p>
  <div class="cards">
    <% @spectacle.performs.each do | perform | %>
      <%= render "performs/small_perform", perform: perform, spectacle:@spectacle %>
    <% end %>
  </div>

  <div class="mt-4">
  <p> <%= link_to "Back to spectacles", spectacles_path %> |
    <%= link_to "Edit this spectacle", edit_spectacle_path(@spectacle) %> |
    <%= link_to "Ajouter une représentation", new_spectacle_perform_path(@spectacle) %> |
    <%= link_to "Delete",
    spectacle_path(@spectacle),
    data: {turbo_method: :delete, turbo_confirm: "delete this spectacle ?"} %>
    </p>

    <%#= button_to "Destroy this spectacle", @spectacle, method: :delete %>
  </div>
</div>